services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
  web-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=test
    command: npm run test # Override the default command to run tests
    depends_on:
      - web
